name: e2e tests on Windows

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

defaults:
  run:
    shell: powershell
jobs:
  e2e-tests:
    timeout-minutes: 90
    runs-on: windows-latest
    steps:
      - name: Update any pre-installed WSL
        run: wsl --update
        continue-on-error: true
      - name: Install WSL2 from the Store as necessary
        run: wsl --install --no-distribution
      - run: wsl --version
      - name: Stop Docker daemon
        run: Stop-Service -Name docker
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      # For compatibility with runners without yarn, we need to install node
      # once, install yarn, then install node again to get caching.
      - uses: actions/setup-node@v4
        with:
          node-version: '18.16.x'
      - run: npm install --global yarn
      - uses: actions/setup-node@v4
        with:
          node-version: '18.16.x'
          cache: yarn
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21'
          cache: 'true'
          cache-dependency-path: src/go/**/go.sum
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install setuptools
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run e2e Tests
        run: yarn test:e2e
        env:
          RD_DEBUG_ENABLED: '1'
      - name: Upload failure reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2etest-artifacts
          path: ./e2e/reports/*
